export type Location = {
  slug: string;
  city: string;
  state: string;
  country: string;
  region: string;
  industryFocus: string[];
  businessContext: string;
  techScene: string;
  population: 'large' | 'medium' | 'small';
};

export const locations: Location[] = [
  // US — Major metros
  {
    slug: 'austin-tx',
    city: 'Austin',
    state: 'TX',
    country: 'US',
    region: 'Texas',
    industryFocus: ['SaaS startups', 'semiconductor manufacturing', 'creator economy'],
    businessContext: 'Austin has become the US capital of tech relocation, with Tesla, Oracle, Apple, and hundreds of startups establishing headquarters after leaving Silicon Valley. The city\'s startup density is among the highest in the country.',
    techScene: 'SXSW, Dell Medical School, and the University of Texas produce a constant pipeline of engineers and entrepreneurs. AI and agentic automation are top priorities for Austin-based SaaS founders.',
    population: 'large',
  },
  {
    slug: 'new-york-ny',
    city: 'New York',
    state: 'NY',
    country: 'US',
    region: 'New York',
    industryFocus: ['financial services', 'media and advertising', 'enterprise SaaS'],
    businessContext: 'New York City is the largest business market in the US, home to more Fortune 500 companies than any other city. Finance, media, healthcare, and professional services firms are the largest buyers of software and AI solutions.',
    techScene: 'NYC\'s AI ecosystem is driven by finance (quant trading, risk modeling), media (personalization, content AI), and an enormous pool of enterprise buyers with high automation budgets.',
    population: 'large',
  },
  {
    slug: 'san-francisco-ca',
    city: 'San Francisco',
    state: 'CA',
    country: 'US',
    region: 'California',
    industryFocus: ['AI and ML', 'venture-backed startups', 'developer tools'],
    businessContext: 'San Francisco and the broader Bay Area remain the global centre of AI research and venture capital. Anthropic, OpenAI, Salesforce, and hundreds of AI-native startups are headquartered here.',
    techScene: 'The SF startup ecosystem moves fast. Founders here are typically early adopters of agentic AI, Claude Code, and MCP-based architectures — looking for technical partners who are already working with the latest tools.',
    population: 'large',
  },
  {
    slug: 'chicago-il',
    city: 'Chicago',
    state: 'IL',
    country: 'US',
    region: 'Midwest',
    industryFocus: ['financial trading', 'logistics and supply chain', 'enterprise manufacturing'],
    businessContext: 'Chicago is the US hub for algorithmic trading, commodities, and enterprise B2B. The city has a massive base of mid-market and enterprise businesses that are actively investing in AI-driven process automation.',
    techScene: 'Chicago\'s AI demand comes from fintech (options trading, risk), logistics (route optimisation, warehouse AI), and enterprise (ERP integration, workflow automation). Healthcare is a fast-growing vertical.',
    population: 'large',
  },
  {
    slug: 'los-angeles-ca',
    city: 'Los Angeles',
    state: 'CA',
    country: 'US',
    region: 'California',
    industryFocus: ['entertainment and media', 'e-commerce', 'real estate technology'],
    businessContext: 'Los Angeles is the world\'s largest entertainment market and a major e-commerce hub. The creator economy, streaming, fashion, and consumer brands drive massive demand for digital product and AI-powered content tools.',
    techScene: 'LA\'s tech scene centres on consumer apps, creator tools, AI video generation, and entertainment. The city produces more AI content startups than anywhere except SF.',
    population: 'large',
  },
  {
    slug: 'seattle-wa',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    region: 'Pacific Northwest',
    industryFocus: ['cloud infrastructure', 'e-commerce technology', 'aerospace'],
    businessContext: 'Seattle is home to Amazon and Microsoft, making it the global capital of cloud computing. The city has a high concentration of senior engineers and a culture that values technical depth over speed.',
    techScene: 'Seattle companies lead in cloud-native AI (AWS Bedrock, Azure OpenAI), data platforms, and developer tools. Enterprise buyers here expect production-grade systems with proper observability and scaling.',
    population: 'large',
  },
  {
    slug: 'boston-ma',
    city: 'Boston',
    state: 'MA',
    country: 'US',
    region: 'New England',
    industryFocus: ['healthcare and biotech', 'edtech', 'financial services'],
    businessContext: 'Boston is the US centre for healthcare AI, biotech, and academic research. MIT, Harvard, and Northeastern produce the country\'s highest concentration of AI researchers. The city\'s healthcare and life sciences verticals are aggressive AI adopters.',
    techScene: 'Boston AI demand is concentrated in clinical AI, drug discovery tooling, research automation, and edtech. Financial services (State Street, Fidelity) are also significant buyers of AI automation.',
    population: 'large',
  },
  {
    slug: 'miami-fl',
    city: 'Miami',
    state: 'FL',
    country: 'US',
    region: 'Florida',
    industryFocus: ['real estate technology', 'fintech and crypto', 'Latin America trade'],
    businessContext: 'Miami has emerged as the gateway between the US and Latin America, with a booming financial services and tech startup scene. Real estate, crypto, and cross-border commerce are the dominant verticals.',
    techScene: 'Miami startups are international by nature, often requiring bilingual AI (English + Spanish), cross-border payment integrations, and real estate tech. The city is also a growing hub for AI-native fintech.',
    population: 'large',
  },
  {
    slug: 'denver-co',
    city: 'Denver',
    state: 'CO',
    country: 'US',
    region: 'Mountain West',
    industryFocus: ['outdoor and recreational industry', 'aerospace and defence', 'cannabis tech'],
    businessContext: 'Denver is one of the fastest-growing US tech markets, with a lower cost base than coastal cities and a strong quality of life attracting engineers. The city\'s startup ecosystem spans outdoor brands, aerospace, and growing enterprise software.',
    techScene: 'Denver companies are increasingly adopting AI for operations, customer support, and supply chain. The city has a strong culture of pragmatic, ROI-driven technology adoption.',
    population: 'large',
  },
  {
    slug: 'atlanta-ga',
    city: 'Atlanta',
    state: 'GA',
    country: 'US',
    region: 'Southeast',
    industryFocus: ['logistics and transportation', 'media and film production', 'financial services'],
    businessContext: 'Atlanta is the logistics capital of the Southeast, home to Hartsfield-Jackson (the world\'s busiest airport), UPS, Delta, and a growing fintech ecosystem. The city is also the centre of US film production outside LA.',
    techScene: 'Atlanta\'s tech scene is maturing rapidly, with strong fintech (Fiserv, NCR, Global Payments all HQ\'d here), logistics AI, and an emerging startup ecosystem centred around Georgia Tech.',
    population: 'large',
  },
  {
    slug: 'dallas-tx',
    city: 'Dallas',
    state: 'TX',
    country: 'US',
    region: 'Texas',
    industryFocus: ['financial services', 'telecommunications', 'healthcare systems'],
    businessContext: 'Dallas is a major corporate headquarters city — AT&T, Southwest Airlines, and dozens of Fortune 500 companies are based here. The DFW metroplex has one of the largest concentrations of corporate buyers outside New York.',
    techScene: 'Dallas AI demand comes from telecom (AI-driven network optimisation), healthcare (patient workflow automation), financial services, and a massive SMB market looking for practical AI solutions.',
    population: 'large',
  },
  {
    slug: 'houston-tx',
    city: 'Houston',
    state: 'TX',
    country: 'US',
    region: 'Texas',
    industryFocus: ['energy and oil and gas', 'healthcare systems', 'port and logistics'],
    businessContext: 'Houston is the energy capital of the world and the largest US city for healthcare. The energy sector is aggressively adopting AI for predictive maintenance, sensor analytics, and operational efficiency.',
    techScene: 'Houston\'s AI market is shaped by energy (digital twin systems, predictive maintenance, field operations), the Texas Medical Center (the largest medical complex globally), and a significant international trade sector.',
    population: 'large',
  },
  {
    slug: 'phoenix-az',
    city: 'Phoenix',
    state: 'AZ',
    country: 'US',
    region: 'Southwest',
    industryFocus: ['semiconductor manufacturing', 'real estate technology', 'financial services'],
    businessContext: 'Phoenix is one of the fastest-growing US metros, with TSMC\'s US semiconductor fab, a major financial services hub, and a real estate market that has consistently ranked in the top 5 for growth.',
    techScene: 'Phoenix businesses are focused on practical AI: customer service automation, real estate lead systems, and the operational needs of a rapidly expanding mid-market business community.',
    population: 'large',
  },
  {
    slug: 'san-diego-ca',
    city: 'San Diego',
    state: 'CA',
    country: 'US',
    region: 'California',
    industryFocus: ['biotech and life sciences', 'defence and military technology', 'telecom'],
    businessContext: 'San Diego is a global leader in biotech — Illumina, Qualcomm, and dozens of biotech firms are headquartered here. The city also has the largest US military presence of any metro, generating significant defence tech demand.',
    techScene: 'San Diego AI is concentrated in healthcare (clinical AI, genomics), defence (autonomous systems, cybersecurity), and telecoms (Qualcomm\'s AI chip research). Life sciences startups are among the most AI-forward buyers.',
    population: 'large',
  },
  {
    slug: 'nashville-tn',
    city: 'Nashville',
    state: 'TN',
    country: 'US',
    region: 'Southeast',
    industryFocus: ['healthcare IT', 'music and entertainment', 'hospitality technology'],
    businessContext: 'Nashville is the US capital of healthcare IT — more healthcare companies are headquartered here per capita than anywhere else in the country. HCA Healthcare, Parallon, and hundreds of healthcare software companies call Nashville home.',
    techScene: 'Nashville AI is dominated by healthcare workflows (prior authorisation, revenue cycle management, clinical documentation). Hospitality and music licensing are secondary AI verticals.',
    population: 'medium',
  },
  {
    slug: 'charlotte-nc',
    city: 'Charlotte',
    state: 'NC',
    country: 'US',
    region: 'Southeast',
    industryFocus: ['banking and financial services', 'energy utilities', 'logistics'],
    businessContext: 'Charlotte is the second-largest US banking hub after New York — Bank of America and Wells Fargo have significant operations here. Financial services firms in Charlotte are active buyers of AI compliance, risk, and customer service tools.',
    techScene: 'Charlotte\'s tech scene is emerging but finance-dominated. AI demand centres on banking automation, regulatory compliance, customer support, and the utility sector\'s grid intelligence needs.',
    population: 'large',
  },
  {
    slug: 'portland-or',
    city: 'Portland',
    state: 'OR',
    country: 'US',
    region: 'Pacific Northwest',
    industryFocus: ['outdoor and lifestyle brands', 'semiconductor design', 'sustainable tech'],
    businessContext: 'Portland is home to Nike, Adidas, Columbia Sportswear, and a growing semiconductor design ecosystem. The city\'s culture of sustainability and craftsmanship extends to its approach to technology — quality and thoughtfulness over speed.',
    techScene: 'Portland companies want AI that is practical and explainable, not flashy demos. Outdoor brands need AI for supply chain and personalisation. Intel has a major design centre here driving semiconductor AI.',
    population: 'medium',
  },
  {
    slug: 'minneapolis-mn',
    city: 'Minneapolis',
    state: 'MN',
    country: 'US',
    region: 'Midwest',
    industryFocus: ['medical devices', 'retail and consumer goods', 'financial services'],
    businessContext: 'Minneapolis is a major corporate headquarters city — Target, Best Buy, 3M, UnitedHealth Group, and Medtronic are all based here. The medical device sector is a significant AI buyer for regulatory documentation and clinical data analysis.',
    techScene: 'Minneapolis AI is driven by medical device (FDA submission automation, device intelligence), retail (personalisation, demand forecasting), and financial services. The city values reliability over novelty.',
    population: 'large',
  },
  {
    slug: 'detroit-mi',
    city: 'Detroit',
    state: 'MI',
    country: 'US',
    region: 'Midwest',
    industryFocus: ['automotive and mobility', 'manufacturing automation', 'logistics'],
    businessContext: 'Detroit is reinventing itself from auto manufacturing to mobility technology. Ford, GM, and Stellantis are all investing aggressively in AI, EVs, and software-defined vehicles — and the supplier ecosystem around them is following.',
    techScene: 'Detroit AI demand centres on manufacturing AI (predictive maintenance, quality control vision), supply chain optimisation, and the mobility software stack (connected vehicles, fleet management).',
    population: 'large',
  },
  {
    slug: 'salt-lake-city-ut',
    city: 'Salt Lake City',
    state: 'UT',
    country: 'US',
    region: 'Mountain West',
    industryFocus: ['SaaS companies', 'outdoor industry', 'healthcare technology'],
    businessContext: 'Salt Lake City\'s "Silicon Slopes" corridor has produced Qualtrics, Domo, and dozens of B2B SaaS companies. Lower cost of living than Bay Area combined with strong engineering talent from BYU and U of U makes it a growing startup hub.',
    techScene: 'Salt Lake City startups are building B2B SaaS, HR tech, and healthcare platforms. AI adoption is fast — the city\'s startup culture is ambitious and AI-forward.',
    population: 'medium',
  },
  {
    slug: 'las-vegas-nv',
    city: 'Las Vegas',
    state: 'NV',
    country: 'US',
    region: 'Southwest',
    industryFocus: ['hospitality and gaming', 'events and convention technology', 'real estate'],
    businessContext: 'Las Vegas processes more hospitality transactions than almost any city on earth. Casinos, hotels, and the event industry generate enormous demand for AI-powered guest experience, dynamic pricing, and operational automation.',
    techScene: 'Las Vegas AI demand is driven by hospitality (personalised guest AI, chatbots, dynamic pricing), event technology, and a growing real estate market. The city\'s businesses need 24/7 AI-powered support systems.',
    population: 'large',
  },
  {
    slug: 'pittsburgh-pa',
    city: 'Pittsburgh',
    state: 'PA',
    country: 'US',
    region: 'Mid-Atlantic',
    industryFocus: ['robotics and AI research', 'healthcare systems', 'steel and manufacturing'],
    businessContext: 'Pittsburgh is home to Carnegie Mellon University — the top US robotics and AI research institution. Waymo and Uber ATG built their self-driving car systems here. The city has a unique combination of deep AI research and heavy industrial buyers.',
    techScene: 'Pittsburgh AI ranges from cutting-edge robotics (CMU spin-offs) to practical manufacturing automation for the city\'s industrial base. UPMC (University of Pittsburgh Medical Center) is a major healthcare AI buyer.',
    population: 'medium',
  },
  {
    slug: 'raleigh-nc',
    city: 'Raleigh',
    state: 'NC',
    country: 'US',
    region: 'Southeast',
    industryFocus: ['biotech and pharma', 'cloud software', 'university research'],
    businessContext: 'The Research Triangle (Raleigh-Durham-Chapel Hill) is one of the densest concentrations of PhD researchers in the US. IBM, Cisco, Red Hat, and hundreds of biotech companies operate here.',
    techScene: 'Raleigh\'s AI market is research-driven — bioinformatics, clinical AI, and enterprise software dominate. The Research Triangle Park is a major hub for enterprise AI infrastructure buying.',
    population: 'large',
  },
  {
    slug: 'tampa-fl',
    city: 'Tampa',
    state: 'FL',
    country: 'US',
    region: 'Florida',
    industryFocus: ['healthcare', 'financial services', 'tourism and hospitality'],
    businessContext: 'Tampa is one of the fastest-growing US metros, with a major financial services hub (Raymond James, WellCare) and healthcare system (Tampa General, BayCare). The city is attracting tech companies with its lower cost base and Florida tax advantages.',
    techScene: 'Tampa AI is growing fast across healthcare, insurance, and financial services. The city\'s SMB market is also significant — many service businesses are deploying AI phone and customer support systems.',
    population: 'large',
  },
  {
    slug: 'san-antonio-tx',
    city: 'San Antonio',
    state: 'TX',
    country: 'US',
    region: 'Texas',
    industryFocus: ['military and defence', 'healthcare', 'tourism and hospitality'],
    businessContext: 'San Antonio has the largest US military base concentration of any metro — Lackland AFB, Fort Sam Houston, and others. This drives significant defence tech and cybersecurity demand. The city is also a major healthcare and tourism centre.',
    techScene: 'San Antonio AI demand comes from government and defence contractors, healthcare (Methodist Healthcare), and a growing startup ecosystem supported by UTSA and UT Health.',
    population: 'large',
  },
  {
    slug: 'indianapolis-in',
    city: 'Indianapolis',
    state: 'IN',
    country: 'US',
    region: 'Midwest',
    industryFocus: ['life sciences and pharma', 'logistics', 'motorsports technology'],
    businessContext: 'Indianapolis is home to Eli Lilly (pharma giant), a major FedEx logistics hub, and the world\'s most famous motor race. Life sciences is the dominant industry, with significant demand for clinical data and regulatory AI.',
    techScene: 'Indianapolis AI centres on life sciences (clinical documentation, regulatory compliance AI), logistics (last-mile optimisation), and an emerging startup scene supported by Salesforce\'s local investment.',
    population: 'large',
  },
  {
    slug: 'columbus-oh',
    city: 'Columbus',
    state: 'OH',
    country: 'US',
    region: 'Midwest',
    industryFocus: ['retail technology', 'insurance', 'education technology'],
    businessContext: 'Columbus is the HQ of JPMorgan Chase\'s technology operations and a major retail tech centre — Limited Brands, Abercrombie, and dozens of direct-to-consumer companies are based here. The city is also home to The Ohio State University.',
    techScene: 'Columbus AI is driven by retail (personalisation, demand forecasting, supply chain), finance (JPMorgan\'s AI research is substantial), and insurance (Nationwide, Progressive are major local employers).',
    population: 'large',
  },
  {
    slug: 'kansas-city-mo',
    city: 'Kansas City',
    state: 'MO',
    country: 'US',
    region: 'Midwest',
    industryFocus: ['logistics and freight', 'agriculture technology', 'financial services'],
    businessContext: 'Kansas City is a logistics and freight crossroads — more rail lines converge here than any US city. Agriculture tech (precision farming, commodity trading platforms) and an emerging startup scene are growing fast.',
    techScene: 'Kansas City AI demand centres on logistics intelligence (real-time tracking, route optimisation), agriculture data platforms, and financial services. The city hosts Sprint and Cerner (Oracle Health) as major enterprise anchors.',
    population: 'medium',
  },
  {
    slug: 'st-louis-mo',
    city: 'St. Louis',
    state: 'MO',
    country: 'US',
    region: 'Midwest',
    industryFocus: ['healthcare and biotech', 'agriculture technology', 'financial services'],
    businessContext: 'St. Louis is a major healthcare hub (BJC HealthCare, Washington University Medical Center) and home to Bayer\'s crop science division and Monsanto\'s successor Bayer CropScience. Agriculture and health AI are the dominant verticals.',
    techScene: 'St. Louis AI is centred on plant science data (precision agriculture, crop modelling), healthcare (clinical analytics, revenue cycle), and a growing fintech cluster in the Cortex Innovation Community.',
    population: 'medium',
  },
  {
    slug: 'boise-id',
    city: 'Boise',
    state: 'ID',
    country: 'US',
    region: 'Pacific Northwest',
    industryFocus: ['semiconductor and tech manufacturing', 'food and agriculture', 'outdoor industry'],
    businessContext: 'Boise is one of the fastest-growing mid-size US metros. Micron Technology (memory chips), HP, and a growing startup ecosystem have made it a significant tech hub. The lower cost of living compared to coastal cities is a major draw.',
    techScene: 'Boise tech companies are practical AI adopters — focused on operational efficiency, customer service automation, and business intelligence rather than cutting-edge research.',
    population: 'small',
  },
  {
    slug: 'orlando-fl',
    city: 'Orlando',
    state: 'FL',
    country: 'US',
    region: 'Florida',
    industryFocus: ['tourism and theme parks', 'simulation and defence technology', 'healthcare'],
    businessContext: 'Orlando is home to Walt Disney World, Universal, and the world\'s largest concentration of theme park technology. Lockheed Martin, Siemens, and a major defence simulation industry also operate here.',
    techScene: 'Orlando AI demand spans hospitality and guest experience (personalisation, AI concierge), defence simulation (training systems, autonomous vehicle testing), and healthcare.',
    population: 'large',
  },
  // International cities
  {
    slug: 'london-uk',
    city: 'London',
    state: 'England',
    country: 'UK',
    region: 'United Kingdom',
    industryFocus: ['financial technology', 'enterprise software', 'media and publishing'],
    businessContext: 'London is Europe\'s financial capital and the largest English-speaking tech market outside the US. The city\'s fintech sector (Revolut, Wise, Monzo were all founded here) leads Europe in AI adoption.',
    techScene: 'London AI spans fintech (fraud detection, KYC automation, trading), enterprise software (many US SaaS companies\' European HQ), and media (The Guardian, Reuters). UK companies are early adopters of agentic AI for professional services.',
    population: 'large',
  },
  {
    slug: 'toronto-canada',
    city: 'Toronto',
    state: 'Ontario',
    country: 'Canada',
    region: 'Canada',
    industryFocus: ['financial services', 'AI research', 'healthcare'],
    businessContext: 'Toronto is a global AI research centre — Geoffrey Hinton\'s work at the University of Toronto helped launch the deep learning era. The Vector Institute, Canada\'s federal AI strategy, and US company expansion have made Toronto a top-5 global AI city.',
    techScene: 'Toronto AI is research-forward but increasingly commercial — financial services (RBC, TD, Scotiabank are aggressive AI buyers), healthcare (Ontario Health AI adoption), and a growing startup ecosystem.',
    population: 'large',
  },
  {
    slug: 'sydney-australia',
    city: 'Sydney',
    state: 'NSW',
    country: 'Australia',
    region: 'Australia',
    industryFocus: ['financial services', 'mining technology', 'retail and e-commerce'],
    businessContext: 'Sydney is Australia\'s financial and tech capital. The Australian government\'s AI Ethics Framework and strong enterprise adoption have made it APAC\'s most mature AI buyer market outside Singapore and Japan.',
    techScene: 'Sydney AI is driven by banking (CBA, Westpac are major AI investors), mining technology (predictive maintenance for remote operations), and retail. Australian businesses prioritise data sovereignty and compliance in AI deployments.',
    population: 'large',
  },
  {
    slug: 'singapore',
    city: 'Singapore',
    state: '',
    country: 'Singapore',
    region: 'Southeast Asia',
    industryFocus: ['financial technology', 'logistics and trade', 'government smart city'],
    businessContext: 'Singapore is Southeast Asia\'s tech hub and one of the world\'s most AI-forward governments. The Smart Nation initiative has driven deep AI adoption across government services, financial institutions, and logistics companies.',
    techScene: 'Singapore AI spans fintech (DBS, OCBC are global AI banking leaders), port and logistics (the world\'s busiest smart port), and enterprise AI for the ASEAN market. English proficiency makes it a natural bridge for US companies entering Asia.',
    population: 'large',
  },
  {
    slug: 'dubai-uae',
    city: 'Dubai',
    state: '',
    country: 'UAE',
    region: 'Middle East',
    industryFocus: ['real estate and property technology', 'tourism and hospitality', 'fintech'],
    businessContext: 'Dubai has declared an ambition to be the world\'s most AI-ready city — the UAE AI Strategy 2031 is one of the world\'s most aggressive national AI plans. Real estate, hospitality, and financial services are the dominant verticals.',
    techScene: 'Dubai AI demand centres on luxury real estate (AI-powered buyer matching, virtual tours), hospitality (personalised guest experience at scale), and a massive government digitalisation programme. Arabic language AI capability is a differentiator here.',
    population: 'large',
  },
  {
    slug: 'melbourne-australia',
    city: 'Melbourne',
    state: 'VIC',
    country: 'Australia',
    region: 'Australia',
    industryFocus: ['education technology', 'healthcare', 'creative industries'],
    businessContext: 'Melbourne is Australia\'s second city and a major centre for healthcare, education, and creative industries. The University of Melbourne and Monash are strong AI research institutions.',
    techScene: 'Melbourne AI spans healthcare (digital health startups, telehealth AI), edtech (Duolingo\'s APAC team is here), and a growing B2B SaaS scene. The city is pragmatic about AI — focused on clear business value over experimentation.',
    population: 'large',
  },
  {
    slug: 'berlin-germany',
    city: 'Berlin',
    state: 'Berlin',
    country: 'Germany',
    region: 'Europe',
    industryFocus: ['startup ecosystem', 'manufacturing tech', 'media and culture'],
    businessContext: 'Berlin is Europe\'s startup capital — N26, Zalando, Delivery Hero, and Klarna all launched here. The city\'s AI scene is younger than London\'s but growing rapidly, with strong EU AI Act compliance expertise.',
    techScene: 'Berlin AI is startup-led, covering fintech, e-commerce personalisation, and creative AI tools. German engineering culture means production-grade reliability is always expected — demo-ware does not pass muster.',
    population: 'large',
  },
  {
    slug: 'amsterdam-netherlands',
    city: 'Amsterdam',
    state: 'Noord-Holland',
    country: 'Netherlands',
    region: 'Europe',
    industryFocus: ['logistics and trade', 'fintech', 'creative technology'],
    businessContext: 'Amsterdam is Europe\'s logistics and trade hub — Schiphol Airport, the Port of Rotterdam, and major shipping companies make the Netherlands the gateway to European markets. Booking.com (AI for travel) and ASML (semiconductor lithography) are major local tech giants.',
    techScene: 'Amsterdam AI covers logistics intelligence, travel tech (Booking.com\'s AI recommendation systems set industry standards), and financial services. Strong EU AI Act awareness makes compliance-first AI approaches highly valued.',
    population: 'large',
  },
  {
    slug: 'vancouver-canada',
    city: 'Vancouver',
    state: 'British Columbia',
    country: 'Canada',
    region: 'Canada',
    industryFocus: ['video game development', 'film and visual effects', 'AI research'],
    businessContext: 'Vancouver is the largest video game hub outside Tokyo and Los Angeles — EA, Activision, and hundreds of studios are based here. The city also has a significant AI research community (DeepMind and Microsoft Research have offices here).',
    techScene: 'Vancouver AI centres on creative AI (game AI, procedural content generation), visual effects, and a growing enterprise tech cluster. US companies frequently establish Canadian operations here for talent and tax advantages.',
    population: 'large',
  },
  {
    slug: 'sao-paulo-brazil',
    city: 'São Paulo',
    state: 'São Paulo',
    country: 'Brazil',
    region: 'Latin America',
    industryFocus: ['financial technology', 'retail and e-commerce', 'healthcare'],
    businessContext: 'São Paulo is Latin America\'s largest economy and financial capital. Nubank, iFood, and dozens of unicorns have launched here. Brazil has 220 million inhabitants and one of the world\'s highest smartphone penetration rates.',
    techScene: 'Brazil AI is driven by fintech (Nubank\'s AI risk models are world-class), e-commerce (personalisation, logistics), and healthcare. Portuguese language AI capability and local compliance knowledge are essential for this market.',
    population: 'large',
  },
  {
    slug: 'zurich-switzerland',
    city: 'Zurich',
    state: 'Zurich',
    country: 'Switzerland',
    region: 'Europe',
    industryFocus: ['banking and wealth management', 'pharmaceutical research', 'enterprise software'],
    businessContext: 'Zurich is the global centre of private banking and wealth management. UBS, Credit Suisse (now UBS), and dozens of private banks generate significant demand for compliance, risk, and client analytics AI.',
    techScene: 'Zurich AI is high-standards and finance-dominated. Swiss Data Protection Act compliance is non-negotiable. ETH Zurich (one of Europe\'s top engineering schools) supplies a strong technical talent base.',
    population: 'medium',
  },
  {
    slug: 'mumbai-india',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    region: 'India',
    industryFocus: ['financial services and banking', 'film and entertainment', 'manufacturing'],
    businessContext: 'Mumbai is India\'s financial capital — home to BSE (Bombay Stock Exchange), RBI, and all major Indian banks. The city is also the centre of Bollywood and a major manufacturing hub.',
    techScene: 'Mumbai AI spans fintech (digital payments, lending AI, KYC), enterprise software, and an enormous SMB market adopting AI for the first time. India\'s talent base and cost advantage make it a major AI development centre globally.',
    population: 'large',
  },
  // More US cities
  {
    slug: 'baltimore-md',
    city: 'Baltimore',
    state: 'MD',
    country: 'US',
    region: 'Mid-Atlantic',
    industryFocus: ['healthcare and life sciences', 'defence technology', 'port and logistics'],
    businessContext: 'Baltimore is a major healthcare and academic research centre — Johns Hopkins Hospital and University are global institutions. The city\'s proximity to Washington DC makes it a significant government and defence tech market.',
    techScene: 'Baltimore AI is dominated by healthcare (Johns Hopkins AI research is world-class), biomedical (research data platforms), and government contracting. Defence cybersecurity and intelligence are significant verticals.',
    population: 'large',
  },
  {
    slug: 'louisville-ky',
    city: 'Louisville',
    state: 'KY',
    country: 'US',
    region: 'Midwest',
    industryFocus: ['healthcare and hospital systems', 'logistics', 'bourbon and food production'],
    businessContext: 'Louisville is a major healthcare hub (Humana, Kindred Healthcare, and Norton Healthcare all HQ here) and a UPS logistics centre. The city\'s healthcare outsourcing industry is significant.',
    techScene: 'Louisville AI centres on healthcare operations (clinical workflow AI, revenue cycle), logistics automation, and an emerging startup ecosystem supported by the Louisville Innovation Network.',
    population: 'medium',
  },
  {
    slug: 'omaha-ne',
    city: 'Omaha',
    state: 'NE',
    country: 'US',
    region: 'Midwest',
    industryFocus: ['financial services', 'insurance', 'telecommunications'],
    businessContext: 'Omaha is a Midwest financial hub — Warren Buffett\'s Berkshire Hathaway, Union Pacific Railroad, and Mutual of Omaha are headquartered here. The city has a quiet but significant financial services tech cluster.',
    techScene: 'Omaha AI is practical and finance-focused — risk analysis, insurance claims automation, and railroad operations intelligence. The city\'s conservative business culture favours proven solutions over experiments.',
    population: 'small',
  },
  {
    slug: 'richmond-va',
    city: 'Richmond',
    state: 'VA',
    country: 'US',
    region: 'Mid-Atlantic',
    industryFocus: ['financial services', 'government and federal contracting', 'tobacco and manufacturing'],
    businessContext: 'Richmond is home to Capital One\'s national operations and a significant federal contracting market given its proximity to Washington DC. The city is growing as a data centre hub due to Virginia\'s incentives.',
    techScene: 'Richmond AI is driven by financial services (Capital One\'s AI research is world-class), federal IT contracting, and a growing data centre ecosystem. Cybersecurity and compliance AI are strong verticals.',
    population: 'medium',
  },
  {
    slug: 'memphis-tn',
    city: 'Memphis',
    state: 'TN',
    country: 'US',
    region: 'Southeast',
    industryFocus: ['logistics and freight', 'healthcare', 'food and agriculture'],
    businessContext: 'Memphis is the FedEx global hub — more packages move through Memphis than almost any city on earth. Logistics technology, supply chain optimisation, and transportation AI are natural fits for the local market.',
    techScene: 'Memphis AI is logistics-first — route optimisation, package tracking AI, warehouse automation, and supply chain intelligence. Healthcare (Methodist Le Bonheur) and agriculture (Mississippi Delta proximity) are secondary verticals.',
    population: 'medium',
  },
  {
    slug: 'albuquerque-nm',
    city: 'Albuquerque',
    state: 'NM',
    country: 'US',
    region: 'Southwest',
    industryFocus: ['semiconductor manufacturing', 'renewable energy', 'government research'],
    businessContext: 'Albuquerque is home to Sandia National Laboratories and Intel\'s chip manufacturing facility. The city has a significant federal research presence and a growing renewable energy sector.',
    techScene: 'Albuquerque AI is research-intensive — Sandia Labs does cutting-edge AI safety research. Semiconductor manufacturing and renewable energy (solar, wind data) are growing AI application areas.',
    population: 'medium',
  },
  {
    slug: 'buffalo-ny',
    city: 'Buffalo',
    state: 'NY',
    country: 'US',
    region: 'New York',
    industryFocus: ['manufacturing', 'healthcare', 'renewable energy'],
    businessContext: 'Buffalo is experiencing a tech renaissance — the Buffalo Billion initiative and proximity to cheap hydro power have attracted major data centre and chip manufacturing investment. New York State semiconductor investments are centred here.',
    techScene: 'Buffalo AI is early-stage but growing fast. Manufacturing intelligence, healthcare (ECMC, Kaleida Health), and energy grid management are the primary AI verticals. The UB (University of Buffalo) is building AI research capacity.',
    population: 'medium',
  },
  {
    slug: 'spokane-wa',
    city: 'Spokane',
    state: 'WA',
    country: 'US',
    region: 'Pacific Northwest',
    industryFocus: ['healthcare', 'agriculture technology', 'logistics'],
    businessContext: 'Spokane is the economic hub of the Inland Northwest — Washington and Idaho\'s agricultural and healthcare industries converge here. Providence Health and Washington State University Spokane anchor the healthcare and research sectors.',
    techScene: 'Spokane AI is practical and sector-specific — precision agriculture (soil sensors, yield prediction), healthcare operations, and logistics for the agricultural supply chain. The city is underserved by tech agencies, creating opportunity.',
    population: 'small',
  },
  {
    slug: 'tucson-az',
    city: 'Tucson',
    state: 'AZ',
    country: 'US',
    region: 'Southwest',
    industryFocus: ['defence and aerospace', 'biosciences', 'solar energy technology'],
    businessContext: 'Tucson is home to Raytheon (now RTX), Davis-Monthan AFB, and the University of Arizona — a powerful combination of defence, aerospace, and research. The city is also a solar energy technology centre.',
    techScene: 'Tucson AI spans defence systems (autonomous vehicles, sensor fusion), aerospace manufacturing intelligence, and renewable energy data analytics. UA (University of Arizona) has a strong AI research programme.',
    population: 'medium',
  },
];

export function getLocationBySlug(slug: string): Location | undefined {
  return locations.find((l) => l.slug === slug);
}

export function getUSLocations(): Location[] {
  return locations.filter((l) => l.country === 'US');
}

export function getInternationalLocations(): Location[] {
  return locations.filter((l) => l.country !== 'US');
}
